import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Home() {
  const TEXT = 'Hello World';
  const router = useRouter();
  const { code } = router.query;
  return (
    <>
      <Head>
        <title>Create Next App </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>{TEXT}</div>
        <div>{code}</div>
      </main>
    </>
  );
}
