import Head from 'next/head';
import { useState, FC } from 'react';

export default function Home() {
  const TEXT = 'Hello World';
  const [check, setCheck] = useState(false);
  const FirstData: any = [
    {
      page_id: 'hoge',
      properties: {
        Checkbox: {
          checkbox: false,
        },
      },
    },
    {
      page_id: 'fuga',
      properties: {
        Checkbox: {
          checkbox: false,
        },
      },
    },
  ];
  //  }
  const inputData = JSON.stringify(FirstData);
  const ChangeCheck = (inputData: string, check: boolean) => {
    let data = JSON.parse(inputData);
    data[0].properties.Checkbox.checkbox = check;
    let outputData = JSON.stringify(data);
    console.log(outputData);

    return outputData;
  };

  return (
    <>
      <Head>
        <title>フラッシュカード</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>{TEXT}</div>
        <div>
          <label>
            <input
              type='checkbox'
              //value=""
              checked={check}
              onChange={() => {
                setCheck((prev) => !prev);
                ChangeCheck(inputData, !check);
              }}
            />
            わかった
          </label>
        </div>
      </main>
    </>
  );
}
